[workspace]

members = [
    "main",
    "home",
    "settings",
    "feed",
    "content",
    "channel",
    "live",
    "utils",
    "components"
]

resolver = "2"

[profile.release]
lto = true
opt-level = 'z'