[package]
name = "content"
version = "0.1.0"
edition = "2021"

[dependencies]
cid = { version = "0.8", default-features = false, features = ["std"] }
yew = { version = "0.19", default-features = false, features = [] }
