[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
linked-data = { git = "https://github.com/Defluencer/rust-defluencer", branch = "develop" }
ipfs-api = { git = "https://github.com/Defluencer/rust-defluencer", branch = "develop" }

cid = { version = "0.8", default-features = false, features = ["std"] }
gloo-console = { version = "0.2", default-features = false, features = [] }
web3 = { version = "0.18", default-features = false, features = ["wasm", "eip-1193"] }
