[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
defluencer = { git = "https://github.com/Defluencer/rust-defluencer", branch = "develop" }
linked-data = { git = "https://github.com/Defluencer/rust-defluencer", branch = "develop" }
ipfs-api = { git = "https://github.com/Defluencer/rust-defluencer", branch = "develop" }


cid = { version = "0.8", default-features = false, features = ["std"] }
gloo-console = { version = "0.2", default-features = false, features = [] }
gloo-storage = { version ="0.2", default-features = false, features = [] }
serde = { version = "1", default-features = false, features = ["std"] }
web3 = { version = "0.18", default-features = false, features = ["wasm", "eip-1193"] }
